import os

ENV = os.environ['ENV']


if ENV == 'local':
    SNOWFLAKE_RESULTS_DB = 'SANDBOX'
elif ENV == 'staging':
    SNOWFLAKE_RESULTS_DB = 'OPERATIONS_STAGING'
elif ENV == 'production':
    SNOWFLAKE_RESULTS_DB = 'OPERATIONS'

SNOWFLAKE_RESULTS_SCHEMA = 'PLAYGROUND' if ENV == 'local' else 'ANALYTICS_OPERATIONS'
SNOWFLAKE_RESULTS_TABLE = 'LUDEOS_METADATA_ANALYSIS'
SNOWFLAKE_READ_DB = f'DATA_WAREHOUSE{"_STAGING" if ENV == "staging" else ""}'
SNOWFLAKE_READ_OPERATIONS_DB = SNOWFLAKE_RESULTS_DB
